name: Version Archiver

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.13.7

      - name: Run versionArchive.py
        run: python /home/runner/work/ArgentumPackages/ArgentumPackages/.github/workflows/versionArchive.py

      - name: Stage, commit, and push
        uses: amousavigourabi/push-action@v0
        with:
          message: Archived current version
